<?php

declare(strict_types=1);

namespace Kosmokrator\Settings;

/**
 * Central registry of all known setting definitions and their aliases.
 *
 * Provides the schema consumed by SettingsManager for validation, categorisation,
 * and dot-path resolution. Definitions are built once and cached statically.
 */
final class SettingsSchema
{
    /** @var array<string, SettingDefinition>|null Cached definitions keyed by canonical ID */
    private static ?array $definitions = null;

    /** @var array<string, string>|null Alias map: short name → canonical dot-path ID */
    private static ?array $aliases = null;

    /**
     * @return array<string, SettingDefinition> All registered definitions keyed by ID
     */
    public function definitions(): array
    {
        return self::$definitions ??= $this->buildDefinitions();
    }

    /**
     * @param  string  $id  Setting identifier (canonical or alias)
     * @return SettingDefinition|null The matching definition, or null if unknown
     */
    public function definition(string $id): ?SettingDefinition
    {
        $canonical = $this->canonicalId($id);

        return $this->definitions()[$canonical] ?? null;
    }

    /**
     * @param  string  $id  A setting ID, possibly an alias
     * @return string The canonical dot-path ID
     */
    public function canonicalId(string $id): string
    {
        if (self::$aliases === null) {
            $this->definitions();
        }

        return self::$aliases[$id] ?? $id;
    }

    /**
     * @return list<string> Category identifiers in display order
     */
    public function categories(): array
    {
        return [
            'general',
            'models',
            'provider_setup',
            'auth',
            'context_memory',
            'agent',
            'permissions',
            'gateway',
            'integrations',
            'mcp',
            'web',
            'subagents',
            'advanced',
            'audio',
        ];
    }

    /**
     * @return array<string, string> Category ID → human-readable label
     */
    public function categoryLabels(): array
    {
        return [
            'general' => 'General',
            'models' => 'Models',
            'provider_setup' => 'Provider Setup',
            'auth' => 'Auth',
            'context_memory' => 'Context & Memory',
            'agent' => 'Agent',
            'permissions' => 'Permissions',
            'gateway' => 'Gateway',
            'integrations' => 'Integrations',
            'mcp' => 'MCP',
            'web' => 'Web',
            'subagents' => 'Subagents',
            'advanced' => 'Advanced',
            'audio' => 'Audio',
        ];
    }

    /**
     * @param  string  $category  Category identifier to filter by
     * @return list<SettingDefinition> Definitions belonging to the given category
     */
    public function definitionsForCategory(string $category): array
    {
        return array_values(array_filter(
            $this->definitions(),
            static fn (SettingDefinition $definition): bool => $definition->category === $category,
        ));
    }

    /** Builds and caches the full definition list and alias map. */
    /**
     * @return array<string, SettingDefinition>
     */
    private function buildDefinitions(): array
    {
        self::$aliases = [
            'mode' => 'agent.mode',
            'permission_mode' => 'tools.default_permission_mode',
            'memories' => 'context.memories',
            'auto_compact' => 'context.auto_compact',
            'compact_threshold' => 'context.compact_threshold',
            'context_reserve_output_tokens' => 'context.reserve_output_tokens',
            'context_warning_buffer_tokens' => 'context.warning_buffer_tokens',
            'context_auto_compact_buffer_tokens' => 'context.auto_compact_buffer_tokens',
            'context_blocking_buffer_tokens' => 'context.blocking_buffer_tokens',
            'prune_protect' => 'context.prune_protect',
            'prune_min_savings' => 'context.prune_min_savings',
            'temperature' => 'agent.temperature',
            'max_tokens' => 'agent.max_tokens',
            'max_retries' => 'agent.max_retries',
            'subagent_max_depth' => 'agent.subagent_max_depth',
            'subagent_concurrency' => 'agent.subagent_concurrency',
            'subagent_max_retries' => 'agent.subagent_max_retries',
            'subagent_idle_watchdog_seconds' => 'agent.subagent_idle_watchdog_seconds',
            'completion_sound' => 'audio.completion_sound',
            'soundfont' => 'audio.soundfont',
            'sound_llm_timeout' => 'audio.llm_timeout',
            'sound_max_duration' => 'audio.max_duration',
            'sound_max_retries' => 'audio.max_retries',
            'system_prompt' => 'agent.system_prompt',
            'max_output_lines' => 'context.max_output_lines',
            'max_output_bytes' => 'context.max_output_bytes',
            'denied_tools' => 'tools.denied_tools',
            'safe_tools' => 'tools.safe_tools',
            'approval_required' => 'tools.approval_required',
            'blocked_paths' => 'tools.blocked_paths',
            'allowed_paths' => 'tools.allowed_paths',
            'guardian_safe_commands' => 'tools.guardian_safe_commands',
            'bash_timeout' => 'tools.bash.timeout',
            'bash_blocked_commands' => 'tools.bash.blocked_commands',
            'shell_wait_ms' => 'tools.shell.wait_ms',
            'shell_idle_ttl' => 'tools.shell.idle_ttl',
            'integrations_permissions_default' => 'integrations.permissions_default',
            'mcp_permissions_default' => 'mcp.permissions_default',
            'show_reasoning' => 'ui.show_reasoning',
            'reasoning_effort' => 'agent.reasoning_effort',
            'subagent_provider' => 'agent.subagent_provider',
            'subagent_model' => 'agent.subagent_model',
            'subagent_depth2_provider' => 'agent.subagent_depth2_provider',
            'subagent_depth2_model' => 'agent.subagent_depth2_model',
            'audio_provider' => 'agent.audio_provider',
            'audio_model' => 'agent.audio_model',
            'web_search_enabled' => 'web.search.enabled',
            'web_search_provider' => 'web.search.provider',
            'web_fetch_provider' => 'web.fetch.provider',
            'web_fetch_allow_external' => 'web.fetch.allow_external',
            'web_crawl_enabled' => 'web.crawl.enabled',
            'web_crawl_provider' => 'web.crawl.provider',
            'web_native_provider' => 'web.native.provider',
            'web_native_mode' => 'web.native.mode',
        ];

        $definitions = [
            new SettingDefinition(
                id: 'ui.renderer',
                path: 'kosmokrator.ui.renderer',
                label: 'Renderer',
                description: 'Preferred renderer for KosmoKrator sessions.',
                category: 'general',
                type: 'choice',
                options: ['auto', 'tui', 'ansi'],
                effect: 'next_session',
                default: 'auto',
            ),
            new SettingDefinition(
                id: 'ui.theme',
                path: 'kosmokrator.ui.theme',
                label: 'Theme',
                description: 'Terminal theme preset.',
                category: 'general',
                type: 'choice',
                options: ['default'],
                effect: 'next_session',
                default: 'default',
            ),
            new SettingDefinition(
                id: 'ui.intro_animated',
                path: 'kosmokrator.ui.intro_animated',
                label: 'Intro animation',
                description: 'Play the startup animation before opening the REPL.',
                category: 'general',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'on',
            ),
            new SettingDefinition(
                id: 'ui.show_reasoning',
                path: 'kosmokrator.ui.show_reasoning',
                label: 'Show reasoning',
                description: 'Display model reasoning/thinking content before each response.',
                category: 'general',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'applies_now',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'agent.default_provider',
                path: 'kosmokrator.agent.default_provider',
                label: 'Default provider',
                description: 'Default provider used when a session starts.',
                category: 'models',
                type: 'dynamic_choice',
                effect: 'next_session',
                default: 'z',
            ),
            new SettingDefinition(
                id: 'agent.default_model',
                path: 'kosmokrator.agent.default_model',
                label: 'Default model',
                description: 'Default model used when a session starts.',
                category: 'models',
                type: 'dynamic_choice',
                effect: 'next_session',
                default: 'glm-5.1',
            ),
            new SettingDefinition(
                id: 'agent.subagent_provider',
                path: 'kosmokrator.agent.subagent_provider',
                label: 'Subagent provider',
                description: 'Provider for depth-1 subagents. Leave empty to inherit the main agent provider.',
                category: 'subagents',
                type: 'dynamic_choice',
                effect: 'next_session',
                default: null,
            ),
            new SettingDefinition(
                id: 'agent.subagent_model',
                path: 'kosmokrator.agent.subagent_model',
                label: 'Subagent model',
                description: 'Model for depth-1 subagents. Leave empty to inherit the main agent model.',
                category: 'subagents',
                type: 'dynamic_choice',
                effect: 'next_session',
                default: null,
            ),
            new SettingDefinition(
                id: 'agent.subagent_depth2_provider',
                path: 'kosmokrator.agent.subagent_depth2_provider',
                label: 'Sub-subagent provider',
                description: 'Provider for depth-2+ subagents. Falls back to subagent provider, then main agent provider.',
                category: 'subagents',
                type: 'dynamic_choice',
                effect: 'next_session',
                default: null,
            ),
            new SettingDefinition(
                id: 'agent.subagent_depth2_model',
                path: 'kosmokrator.agent.subagent_depth2_model',
                label: 'Sub-subagent model',
                description: 'Model for depth-2+ subagents. Falls back to subagent model, then main agent model.',
                category: 'subagents',
                type: 'dynamic_choice',
                effect: 'next_session',
                default: null,
            ),
            new SettingDefinition(
                id: 'agent.audio_provider',
                path: 'kosmokrator.agent.audio_provider',
                label: 'Audio provider',
                description: 'Provider for completion sound music composition. Leave empty to inherit the main agent provider.',
                category: 'audio',
                type: 'dynamic_choice',
                effect: 'next_session',
                default: null,
            ),
            new SettingDefinition(
                id: 'agent.audio_model',
                path: 'kosmokrator.agent.audio_model',
                label: 'Audio model',
                description: 'Model for completion sound music composition. Leave empty to inherit the main agent model.',
                category: 'audio',
                type: 'dynamic_choice',
                effect: 'next_session',
                default: null,
            ),
            new SettingDefinition(
                id: 'agent.mode',
                path: 'kosmokrator.agent.mode',
                label: 'Default mode',
                description: 'Starting mode for interactive sessions.',
                category: 'agent',
                type: 'choice',
                options: ['edit', 'plan', 'ask'],
                effect: 'applies_now',
                default: 'edit',
            ),
            new SettingDefinition(
                id: 'tools.default_permission_mode',
                path: 'kosmokrator.tools.default_permission_mode',
                label: 'Permission mode',
                description: 'Default permission policy for tool calls.',
                category: 'permissions',
                type: 'choice',
                options: ['guardian', 'argus', 'prometheus'],
                effect: 'applies_now',
                default: 'guardian',
            ),
            new SettingDefinition(
                id: 'tools.denied_tools',
                path: 'kosmokrator.tools.denied_tools',
                label: 'Denied tools',
                description: 'Tool names that are always denied, overriding permission mode.',
                category: 'permissions',
                type: 'string_list',
                effect: 'next_session',
                default: [],
            ),
            new SettingDefinition(
                id: 'tools.safe_tools',
                path: 'kosmokrator.tools.safe_tools',
                label: 'Safe tools',
                description: 'Tool names treated as safe under normal permission policy.',
                category: 'permissions',
                type: 'string_list',
                effect: 'next_session',
                default: [],
            ),
            new SettingDefinition(
                id: 'tools.approval_required',
                path: 'kosmokrator.tools.approval_required',
                label: 'Approval-required tools',
                description: 'Tool names that require permission approval unless policy bypasses them.',
                category: 'permissions',
                type: 'string_list',
                effect: 'next_session',
                default: [],
            ),
            new SettingDefinition(
                id: 'tools.blocked_paths',
                path: 'kosmokrator.tools.blocked_paths',
                label: 'Blocked paths',
                description: 'Glob patterns blocked for file tools.',
                category: 'permissions',
                type: 'string_list',
                effect: 'next_session',
                default: [],
            ),
            new SettingDefinition(
                id: 'tools.allowed_paths',
                path: 'kosmokrator.tools.allowed_paths',
                label: 'Allowed paths',
                description: 'Path allowlist that supplements project-local access.',
                category: 'permissions',
                type: 'string_list',
                effect: 'next_session',
                default: [],
            ),
            new SettingDefinition(
                id: 'tools.guardian_safe_commands',
                path: 'kosmokrator.tools.guardian_safe_commands',
                label: 'Guardian safe commands',
                description: 'Shell command glob patterns that Guardian can auto-approve.',
                category: 'permissions',
                type: 'string_list',
                effect: 'next_session',
                default: [],
            ),
            new SettingDefinition(
                id: 'tools.bash.timeout',
                path: 'kosmokrator.tools.bash.timeout',
                label: 'Bash timeout',
                description: 'Default bash command timeout in seconds.',
                category: 'advanced',
                type: 'number',
                effect: 'next_session',
                default: 120,
            ),
            new SettingDefinition(
                id: 'tools.bash.blocked_commands',
                path: 'kosmokrator.tools.bash.blocked_commands',
                label: 'Blocked bash commands',
                description: 'Shell command patterns that are always denied.',
                category: 'advanced',
                type: 'string_list',
                effect: 'next_session',
                default: [],
            ),
            new SettingDefinition(
                id: 'tools.shell.wait_ms',
                path: 'kosmokrator.tools.shell.wait_ms',
                label: 'Shell wait milliseconds',
                description: 'Default wait time for incremental shell sessions.',
                category: 'advanced',
                type: 'number',
                effect: 'next_session',
                default: 100,
            ),
            new SettingDefinition(
                id: 'tools.shell.idle_ttl',
                path: 'kosmokrator.tools.shell.idle_ttl',
                label: 'Shell idle TTL',
                description: 'Seconds before idle shell sessions are cleaned up.',
                category: 'advanced',
                type: 'number',
                effect: 'next_session',
                default: 300,
            ),
            new SettingDefinition(
                id: 'gateway.telegram.enabled',
                path: 'kosmokrator.gateway.telegram.enabled',
                label: 'Telegram gateway',
                description: 'Enable the Telegram gateway worker.',
                category: 'gateway',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'gateway.telegram.session_mode',
                path: 'kosmokrator.gateway.telegram.session_mode',
                label: 'Session routing',
                description: 'How Telegram group messages map to Kosmo sessions.',
                category: 'gateway',
                type: 'choice',
                options: ['thread', 'thread_user', 'chat', 'chat_user'],
                effect: 'next_session',
                default: 'thread',
            ),
            new SettingDefinition(
                id: 'gateway.telegram.allowed_users',
                path: 'kosmokrator.gateway.telegram.allowed_users',
                label: 'Allowed users',
                description: 'Space- or comma-separated Telegram user IDs or usernames. Leave empty to allow any user that can reach the bot.',
                category: 'gateway',
                type: 'string_list',
                effect: 'next_session',
                default: [],
            ),
            new SettingDefinition(
                id: 'gateway.telegram.allowed_chats',
                path: 'kosmokrator.gateway.telegram.allowed_chats',
                label: 'Allowed chats',
                description: 'Space- or comma-separated chat IDs allowed to talk to the bot. Leave empty to allow all chats.',
                category: 'gateway',
                type: 'string_list',
                effect: 'next_session',
                default: [],
            ),
            new SettingDefinition(
                id: 'gateway.telegram.require_mention',
                path: 'kosmokrator.gateway.telegram.require_mention',
                label: 'Require mention in groups',
                description: 'In non-private chats, only respond when mentioned or replied to unless the chat is marked as free-response.',
                category: 'gateway',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'on',
            ),
            new SettingDefinition(
                id: 'gateway.telegram.free_response_chats',
                path: 'kosmokrator.gateway.telegram.free_response_chats',
                label: 'Free-response chats',
                description: 'Space- or comma-separated chat IDs where the bot may answer without an explicit mention.',
                category: 'gateway',
                type: 'string_list',
                effect: 'next_session',
                default: [],
            ),
            new SettingDefinition(
                id: 'gateway.telegram.poll_timeout_seconds',
                path: 'kosmokrator.gateway.telegram.poll_timeout_seconds',
                label: 'Poll timeout',
                description: 'Long-poll timeout in seconds for Telegram update fetches.',
                category: 'gateway',
                type: 'number',
                effect: 'next_session',
                default: 20,
            ),
            new SettingDefinition(
                id: 'integrations.permissions_default',
                path: 'kosmokrator.integrations.permissions_default',
                label: 'Integration default permission',
                description: 'Default read/write permission for integrations without explicit policy.',
                category: 'integrations',
                type: 'choice',
                options: ['allow', 'ask', 'deny'],
                effect: 'applies_now',
                default: 'ask',
            ),
            new SettingDefinition(
                id: 'mcp.permissions_default',
                path: 'kosmokrator.mcp.permissions_default',
                label: 'MCP default permission',
                description: 'Default read/write permission for MCP server operations without explicit policy.',
                category: 'mcp',
                type: 'choice',
                options: ['allow', 'ask', 'deny'],
                effect: 'applies_now',
                default: 'ask',
            ),
            new SettingDefinition(
                id: 'web.search.enabled',
                path: 'kosmokrator.web.search.enabled',
                label: 'Web search',
                description: 'Enable the optional external web_search tool.',
                category: 'web',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'web.search.provider',
                path: 'kosmokrator.web.search.provider',
                label: 'Search provider',
                description: 'Default provider for web_search.',
                category: 'web',
                type: 'choice',
                options: ['tavily', 'firecrawl', 'exa', 'brave', 'parallel', 'jina', 'searxng', 'perplexity', 'openai_native', 'anthropic_native'],
                effect: 'next_session',
                default: null,
            ),
            new SettingDefinition(
                id: 'web.search.max_results',
                path: 'kosmokrator.web.search.max_results',
                label: 'Search max results',
                description: 'Default number of web_search results.',
                category: 'web',
                type: 'number',
                effect: 'next_session',
                default: 8,
            ),
            new SettingDefinition(
                id: 'web.fetch.provider',
                path: 'kosmokrator.web.fetch.provider',
                label: 'Fetch provider',
                description: 'Default fetch provider. Native keeps the built-in web_fetch path.',
                category: 'web',
                type: 'choice',
                options: ['native', 'tavily', 'firecrawl', 'exa', 'parallel', 'jina'],
                effect: 'next_session',
                default: 'native',
            ),
            new SettingDefinition(
                id: 'web.fetch.allow_external',
                path: 'kosmokrator.web.fetch.allow_external',
                label: 'External fetch',
                description: 'Allow web_fetch_external and web_extract provider calls.',
                category: 'web',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'web.crawl.enabled',
                path: 'kosmokrator.web.crawl.enabled',
                label: 'Web crawl',
                description: 'Enable the optional web_crawl tool.',
                category: 'web',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'web.crawl.provider',
                path: 'kosmokrator.web.crawl.provider',
                label: 'Crawl provider',
                description: 'Default provider for web_crawl.',
                category: 'web',
                type: 'choice',
                options: ['tavily', 'firecrawl'],
                effect: 'next_session',
                default: null,
            ),
            new SettingDefinition(
                id: 'web.native.provider',
                path: 'kosmokrator.web.native.provider',
                label: 'Native search provider',
                description: 'Provider-native web search backend for web_search.',
                category: 'web',
                type: 'choice',
                options: ['openai_native', 'anthropic_native'],
                effect: 'next_session',
                default: null,
            ),
            new SettingDefinition(
                id: 'web.native.mode',
                path: 'kosmokrator.web.native.mode',
                label: 'Native search mode',
                description: 'Cached uses provider-managed web search when supported; live asks for fresh external access.',
                category: 'web',
                type: 'choice',
                options: ['cached', 'live'],
                effect: 'next_session',
                default: 'cached',
            ),
            new SettingDefinition(
                id: 'web.providers.tavily.enabled',
                path: 'kosmokrator.web.providers.tavily.enabled',
                label: 'Tavily',
                description: 'Enable Tavily as an external web provider.',
                category: 'web',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'web.providers.firecrawl.enabled',
                path: 'kosmokrator.web.providers.firecrawl.enabled',
                label: 'Firecrawl',
                description: 'Enable Firecrawl as an external web provider.',
                category: 'web',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'web.providers.exa.enabled',
                path: 'kosmokrator.web.providers.exa.enabled',
                label: 'Exa',
                description: 'Enable Exa as an external web provider.',
                category: 'web',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'web.providers.brave.enabled',
                path: 'kosmokrator.web.providers.brave.enabled',
                label: 'Brave Search',
                description: 'Enable Brave Search as an external web provider.',
                category: 'web',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'web.providers.parallel.enabled',
                path: 'kosmokrator.web.providers.parallel.enabled',
                label: 'Parallel',
                description: 'Enable Parallel as an external web provider.',
                category: 'web',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'web.providers.jina.enabled',
                path: 'kosmokrator.web.providers.jina.enabled',
                label: 'Jina Reader',
                description: 'Enable Jina Reader/Search as an external web provider.',
                category: 'web',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'web.providers.searxng.enabled',
                path: 'kosmokrator.web.providers.searxng.enabled',
                label: 'SearXNG',
                description: 'Enable a configured SearXNG instance as an external web provider.',
                category: 'web',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'web.providers.searxng.base_url',
                path: 'kosmokrator.web.providers.searxng.base_url',
                label: 'SearXNG URL',
                description: 'Base URL for a trusted SearXNG instance.',
                category: 'web',
                type: 'text',
                effect: 'next_session',
                default: null,
            ),
            new SettingDefinition(
                id: 'web.providers.perplexity.enabled',
                path: 'kosmokrator.web.providers.perplexity.enabled',
                label: 'Perplexity',
                description: 'Enable Perplexity as an external web search provider.',
                category: 'web',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'web.providers.openai_native.enabled',
                path: 'kosmokrator.web.providers.openai_native.enabled',
                label: 'OpenAI native search',
                description: 'Enable OpenAI Responses web search as a web provider.',
                category: 'web',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'web.providers.anthropic_native.enabled',
                path: 'kosmokrator.web.providers.anthropic_native.enabled',
                label: 'Anthropic native search',
                description: 'Enable Anthropic server-side web search as a web provider.',
                category: 'web',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_session',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'context.memories',
                path: 'kosmokrator.context.memories',
                label: 'Memories',
                description: 'Enable memory recall and persistence features.',
                category: 'context_memory',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_turn',
                default: 'on',
            ),
            new SettingDefinition(
                id: 'context.auto_compact',
                path: 'kosmokrator.context.auto_compact',
                label: 'Auto compact',
                description: 'Compact context automatically before hitting the model limit.',
                category: 'context_memory',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'next_turn',
                default: 'on',
            ),
            new SettingDefinition(
                id: 'context.compact_threshold',
                path: 'kosmokrator.context.compact_threshold',
                label: 'Compact threshold',
                description: 'Legacy threshold percentage for compaction fallback.',
                category: 'context_memory',
                type: 'number',
                effect: 'next_turn',
                default: 60,
            ),
            new SettingDefinition(
                id: 'context.reserve_output_tokens',
                path: 'kosmokrator.context.reserve_output_tokens',
                label: 'Reserved output tokens',
                description: 'Headroom reserved for the assistant response.',
                category: 'context_memory',
                type: 'number',
                effect: 'next_turn',
                default: 16000,
            ),
            new SettingDefinition(
                id: 'context.warning_buffer_tokens',
                path: 'kosmokrator.context.warning_buffer_tokens',
                label: 'Warning buffer',
                description: 'When remaining input budget drops below this, show warnings.',
                category: 'context_memory',
                type: 'number',
                effect: 'next_turn',
                default: 24000,
            ),
            new SettingDefinition(
                id: 'context.auto_compact_buffer_tokens',
                path: 'kosmokrator.context.auto_compact_buffer_tokens',
                label: 'Auto compact buffer',
                description: 'When remaining input budget drops below this, auto compact.',
                category: 'context_memory',
                type: 'number',
                effect: 'next_turn',
                default: 12000,
            ),
            new SettingDefinition(
                id: 'context.blocking_buffer_tokens',
                path: 'kosmokrator.context.blocking_buffer_tokens',
                label: 'Blocking buffer',
                description: 'Hard stop buffer to prevent overrunning the model context window.',
                category: 'context_memory',
                type: 'number',
                effect: 'next_turn',
                default: 3000,
            ),
            new SettingDefinition(
                id: 'context.prune_protect',
                path: 'kosmokrator.context.prune_protect',
                label: 'Prune protect',
                description: 'Recent tool-result tokens protected from micro pruning.',
                category: 'context_memory',
                type: 'number',
                effect: 'next_turn',
                default: 40000,
            ),
            new SettingDefinition(
                id: 'context.prune_min_savings',
                path: 'kosmokrator.context.prune_min_savings',
                label: 'Prune minimum savings',
                description: 'Minimum savings required before a prune pass is accepted.',
                category: 'context_memory',
                type: 'number',
                effect: 'next_turn',
                default: 20000,
            ),
            new SettingDefinition(
                id: 'context.max_output_lines',
                path: 'kosmokrator.context.max_output_lines',
                label: 'Max output lines',
                description: 'Maximum number of tool-output lines retained in context.',
                category: 'context_memory',
                type: 'number',
                effect: 'next_turn',
                default: 2000,
            ),
            new SettingDefinition(
                id: 'context.max_output_bytes',
                path: 'kosmokrator.context.max_output_bytes',
                label: 'Max output bytes',
                description: 'Maximum bytes of tool output retained in context.',
                category: 'context_memory',
                type: 'number',
                effect: 'next_turn',
                default: 50000,
            ),
            new SettingDefinition(
                id: 'agent.reasoning_effort',
                path: 'kosmokrator.agent.reasoning_effort',
                label: 'Reasoning effort',
                description: 'Controls extended thinking/reasoning for supported models. Off disables reasoning params entirely.',
                category: 'agent',
                type: 'choice',
                options: ['off', 'low', 'medium', 'high'],
                effect: 'applies_now',
                default: 'high',
            ),
            new SettingDefinition(
                id: 'agent.system_prompt',
                path: 'kosmokrator.agent.system_prompt',
                label: 'System prompt',
                description: 'Base system prompt used for agent sessions.',
                category: 'advanced',
                type: 'text',
                effect: 'next_session',
                default: null,
            ),
            new SettingDefinition(
                id: 'agent.temperature',
                path: 'kosmokrator.agent.temperature',
                label: 'Temperature',
                description: 'Sampling temperature for supported models.',
                category: 'agent',
                type: 'number',
                effect: 'applies_now',
                default: 0.0,
            ),
            new SettingDefinition(
                id: 'agent.max_tokens',
                path: 'kosmokrator.agent.max_tokens',
                label: 'Max output tokens',
                description: 'Override the model default output token limit.',
                category: 'agent',
                type: 'number',
                effect: 'applies_now',
                default: null,
            ),
            new SettingDefinition(
                id: 'agent.max_retries',
                path: 'kosmokrator.agent.max_retries',
                label: 'Max retries',
                description: 'Retry limit for transient provider failures.',
                category: 'agent',
                type: 'number',
                effect: 'applies_now',
                default: 0,
            ),
            new SettingDefinition(
                id: 'agent.subagent_max_depth',
                path: 'kosmokrator.agent.subagent_max_depth',
                label: 'Subagent max depth',
                description: 'Maximum depth for spawned agent trees.',
                category: 'subagents',
                type: 'number',
                effect: 'next_session',
                default: 3,
            ),
            new SettingDefinition(
                id: 'agent.subagent_concurrency',
                path: 'kosmokrator.agent.subagent_concurrency',
                label: 'Subagent concurrency',
                description: 'Maximum concurrent subagents.',
                category: 'subagents',
                type: 'number',
                effect: 'next_session',
                default: 10,
            ),
            new SettingDefinition(
                id: 'agent.subagent_max_retries',
                path: 'kosmokrator.agent.subagent_max_retries',
                label: 'Subagent retries',
                description: 'Retry limit for transient subagent failures.',
                category: 'subagents',
                type: 'number',
                effect: 'next_session',
                default: 2,
            ),
            new SettingDefinition(
                id: 'agent.subagent_idle_watchdog_seconds',
                path: 'kosmokrator.agent.subagent_idle_watchdog_seconds',
                label: 'Idle watchdog seconds',
                description: 'Cancel only when a running subagent stops making progress updates for too long. Set 0 to disable.',
                category: 'subagents',
                type: 'number',
                effect: 'next_session',
                default: 900,
            ),
            new SettingDefinition(
                id: 'audio.completion_sound',
                path: 'kosmokrator.audio.completion_sound',
                label: 'Play completion sound',
                description: 'Compose and play a short musical piece after each agent response. The music reflects what happened.',
                category: 'audio',
                type: 'toggle',
                options: ['on', 'off'],
                effect: 'applies_now',
                default: 'off',
            ),
            new SettingDefinition(
                id: 'audio.soundfont',
                path: 'kosmokrator.audio.soundfont',
                label: 'Soundfont path',
                description: 'Path to the SoundFont (.sf2) file for MIDI playback.',
                category: 'audio',
                type: 'text',
                effect: 'applies_now',
                default: '~/.kosmokrator/soundfonts/FluidR3_GM.sf2',
            ),
            new SettingDefinition(
                id: 'audio.llm_timeout',
                path: 'kosmokrator.audio.llm_timeout',
                label: 'Composition timeout (seconds)',
                description: 'Seconds to wait for AI music composition before falling back to a built-in omen.',
                category: 'audio',
                type: 'number',
                effect: 'applies_now',
                default: 60,
            ),
            new SettingDefinition(
                id: 'audio.max_duration',
                path: 'kosmokrator.audio.max_duration',
                label: 'Max duration (seconds)',
                description: 'Maximum length of the composed musical piece.',
                category: 'audio',
                type: 'number',
                effect: 'applies_now',
                default: 8,
            ),
            new SettingDefinition(
                id: 'audio.max_retries',
                path: 'kosmokrator.audio.max_retries',
                label: 'Composition retries',
                description: 'Number of times to retry if the LLM fails to generate a valid music script.',
                category: 'audio',
                type: 'number',
                effect: 'applies_now',
                default: 1,
            ),
        ];

        return array_reduce(
            $definitions,
            static function (array $carry, SettingDefinition $definition): array {
                $carry[$definition->id] = $definition;

                return $carry;
            },
            [],
        );
    }
}
